/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BeneficiaryRegistry } from "./BeneficiaryRegistry";
export type { IGovernmentRegistry } from "./IGovernmentRegistry";
export type { IJuryStaking } from "./IJuryStaking";
