/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IBeneficiaryRegistryErc20Interface extends Interface {
  getFunction(nameOrSignature: "isApproved" | "walletOf"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isApproved",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "walletOf", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "isApproved", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "walletOf", data: BytesLike): Result;
}

export interface IBeneficiaryRegistryErc20 extends BaseContract {
  connect(runner?: ContractRunner | null): IBeneficiaryRegistryErc20;
  waitForDeployment(): Promise<this>;

  interface: IBeneficiaryRegistryErc20Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isApproved: TypedContractMethod<
    [beneficiaryId: BytesLike],
    [boolean],
    "view"
  >;

  walletOf: TypedContractMethod<[beneficiaryId: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isApproved"
  ): TypedContractMethod<[beneficiaryId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "walletOf"
  ): TypedContractMethod<[beneficiaryId: BytesLike], [string], "view">;

  filters: {};
}
