/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBeneficiaryRegistryErc20 } from "./IBeneficiaryRegistryErc20";
export type { IERC20 } from "./IERC20";
export type { MonadReliefERC20 } from "./MonadReliefERC20";
