/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MonadReliefInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "beneficiaries"
      | "donate"
      | "donorHasDonated"
      | "governance"
      | "registerBeneficiary"
      | "setVerified"
      | "totalDisbursed"
      | "totalDonationCount"
      | "totalDonations"
      | "uniqueDonorCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BeneficiaryRegistered"
      | "BeneficiaryVerified"
      | "Disbursement"
      | "Donation"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "beneficiaries",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "donate", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "donorHasDonated",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerBeneficiary",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerified",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDisbursed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDonationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDonations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniqueDonorCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "beneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "donorHasDonated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDisbursed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDonationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDonations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniqueDonorCount",
    data: BytesLike
  ): Result;
}

export namespace BeneficiaryRegisteredEvent {
  export type InputTuple = [id: BytesLike, wallet: AddressLike];
  export type OutputTuple = [id: string, wallet: string];
  export interface OutputObject {
    id: string;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeneficiaryVerifiedEvent {
  export type InputTuple = [id: BytesLike, wallet: AddressLike];
  export type OutputTuple = [id: string, wallet: string];
  export interface OutputObject {
    id: string;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisbursementEvent {
  export type InputTuple = [
    beneficiaryId: BytesLike,
    wallet: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    beneficiaryId: string,
    wallet: string,
    amount: bigint
  ];
  export interface OutputObject {
    beneficiaryId: string;
    wallet: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonationEvent {
  export type InputTuple = [
    donor: AddressLike,
    amount: BigNumberish,
    beneficiaryId: BytesLike
  ];
  export type OutputTuple = [
    donor: string,
    amount: bigint,
    beneficiaryId: string
  ];
  export interface OutputObject {
    donor: string;
    amount: bigint;
    beneficiaryId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MonadRelief extends BaseContract {
  connect(runner?: ContractRunner | null): MonadRelief;
  waitForDeployment(): Promise<this>;

  interface: MonadReliefInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  beneficiaries: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, boolean, bigint] & {
        wallet: string;
        verified: boolean;
        totalReceived: bigint;
      }
    ],
    "view"
  >;

  donate: TypedContractMethod<[beneficiaryId: BytesLike], [void], "payable">;

  donorHasDonated: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  governance: TypedContractMethod<[], [string], "view">;

  registerBeneficiary: TypedContractMethod<
    [id: BytesLike, wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setVerified: TypedContractMethod<
    [id: BytesLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  totalDisbursed: TypedContractMethod<[], [bigint], "view">;

  totalDonationCount: TypedContractMethod<[], [bigint], "view">;

  totalDonations: TypedContractMethod<[], [bigint], "view">;

  uniqueDonorCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "beneficiaries"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, boolean, bigint] & {
        wallet: string;
        verified: boolean;
        totalReceived: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<[beneficiaryId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "donorHasDonated"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "governance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerBeneficiary"
  ): TypedContractMethod<
    [id: BytesLike, wallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVerified"
  ): TypedContractMethod<
    [id: BytesLike, verified: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalDisbursed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDonationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDonations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "uniqueDonorCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "BeneficiaryRegistered"
  ): TypedContractEvent<
    BeneficiaryRegisteredEvent.InputTuple,
    BeneficiaryRegisteredEvent.OutputTuple,
    BeneficiaryRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "BeneficiaryVerified"
  ): TypedContractEvent<
    BeneficiaryVerifiedEvent.InputTuple,
    BeneficiaryVerifiedEvent.OutputTuple,
    BeneficiaryVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Disbursement"
  ): TypedContractEvent<
    DisbursementEvent.InputTuple,
    DisbursementEvent.OutputTuple,
    DisbursementEvent.OutputObject
  >;
  getEvent(
    key: "Donation"
  ): TypedContractEvent<
    DonationEvent.InputTuple,
    DonationEvent.OutputTuple,
    DonationEvent.OutputObject
  >;

  filters: {
    "BeneficiaryRegistered(bytes32,address)": TypedContractEvent<
      BeneficiaryRegisteredEvent.InputTuple,
      BeneficiaryRegisteredEvent.OutputTuple,
      BeneficiaryRegisteredEvent.OutputObject
    >;
    BeneficiaryRegistered: TypedContractEvent<
      BeneficiaryRegisteredEvent.InputTuple,
      BeneficiaryRegisteredEvent.OutputTuple,
      BeneficiaryRegisteredEvent.OutputObject
    >;

    "BeneficiaryVerified(bytes32,address)": TypedContractEvent<
      BeneficiaryVerifiedEvent.InputTuple,
      BeneficiaryVerifiedEvent.OutputTuple,
      BeneficiaryVerifiedEvent.OutputObject
    >;
    BeneficiaryVerified: TypedContractEvent<
      BeneficiaryVerifiedEvent.InputTuple,
      BeneficiaryVerifiedEvent.OutputTuple,
      BeneficiaryVerifiedEvent.OutputObject
    >;

    "Disbursement(bytes32,address,uint256)": TypedContractEvent<
      DisbursementEvent.InputTuple,
      DisbursementEvent.OutputTuple,
      DisbursementEvent.OutputObject
    >;
    Disbursement: TypedContractEvent<
      DisbursementEvent.InputTuple,
      DisbursementEvent.OutputTuple,
      DisbursementEvent.OutputObject
    >;

    "Donation(address,uint256,bytes32)": TypedContractEvent<
      DonationEvent.InputTuple,
      DonationEvent.OutputTuple,
      DonationEvent.OutputObject
    >;
    Donation: TypedContractEvent<
      DonationEvent.InputTuple,
      DonationEvent.OutputTuple,
      DonationEvent.OutputObject
    >;
  };
}
