/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBeneficiaryRegistryErc20__factory } from "./IBeneficiaryRegistryErc20__factory";
export { IERC20__factory } from "./IERC20__factory";
export { MonadReliefERC20__factory } from "./MonadReliefERC20__factory";
