/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as beneficiaryRegistrySol from "./BeneficiaryRegistry.sol";
export * as governmentRegistrySol from "./GovernmentRegistry.sol";
export * as monadReliefErc20Sol from "./MonadReliefERC20.sol";
export * as monadReliefV2Sol from "./MonadReliefV2.sol";
export { JuryStaking__factory } from "./JuryStaking__factory";
export { MockUSD__factory } from "./MockUSD__factory";
export { MonadRelief__factory } from "./MonadRelief__factory";
