/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGovernmentRegistry,
  IGovernmentRegistryInterface,
} from "../../BeneficiaryRegistry.sol/IGovernmentRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "walletToTokenId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGovernmentRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IGovernmentRegistryInterface {
    return new Interface(_abi) as IGovernmentRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGovernmentRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IGovernmentRegistry;
  }
}
