/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BeneficiaryRegistry__factory } from "./BeneficiaryRegistry__factory";
export { IGovernmentRegistry__factory } from "./IGovernmentRegistry__factory";
export { IJuryStaking__factory } from "./IJuryStaking__factory";
