/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernmentRegistry } from "./GovernmentRegistry";
export type { IERC165 } from "./IERC165";
export type { IERC721 } from "./IERC721";
