/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernmentRegistry__factory } from "./GovernmentRegistry__factory";
export { IERC165__factory } from "./IERC165__factory";
export { IERC721__factory } from "./IERC721__factory";
