/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBeneficiaryRegistry } from "./IBeneficiaryRegistry";
export type { MonadReliefV2 } from "./MonadReliefV2";
