/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBeneficiaryRegistry,
  IBeneficiaryRegistryInterface,
} from "../../MonadReliefV2.sol/IBeneficiaryRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "beneficiaryId",
        type: "bytes32",
      },
    ],
    name: "isApproved",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "beneficiaryId",
        type: "bytes32",
      },
    ],
    name: "walletOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBeneficiaryRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IBeneficiaryRegistryInterface {
    return new Interface(_abi) as IBeneficiaryRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBeneficiaryRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBeneficiaryRegistry;
  }
}
