/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBeneficiaryRegistry__factory } from "./IBeneficiaryRegistry__factory";
export { MonadReliefV2__factory } from "./MonadReliefV2__factory";
